### ISSUE TITLE
After Suite Error

### ISSUE THREAD

**Issue by GabrielShaukan** [citrusframework/citrus#442]
I get an after suite error with this code 

	
    public class ActivateAutomaticImportAfterSuite extends TestDesignerAfterSuiteSupport {
	   public static final String SD_MANAGER_CLIENT_AUTH = "sdManagerClientAuth";
	
	   @Override
	   public void afterSuite(TestDesigner designer) {
		   designer.echo("hi!!");
		   designer.http().client(SD_MANAGER_CLIENT_AUTH)
			   .send()
			   .post("import/enable-scheduling");
		   designer.http().client(SD_MANAGER_CLIENT_AUTH)
			   .receive()
		   	   .response(HttpStatus.OK);
	   }                      
    }

this is the error:

> 16:08:32.046 [Thread-1] ERROR com.consol.citrus.container.SequenceAfterSuite - After suite action failed receiveNested exception is: 
> java.lang.IllegalStateException: org.springframework.context.support.GenericApplicationContext@cb51256 has been closed already
> 	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1064)
> 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1085)
> 	at com.consol.citrus.endpoint.DefaultEndpointFactory.create(DefaultEndpointFactory.java:96)
> 	at com.consol.citrus.actions.ReceiveMessageAction.getOrCreateEndpoint(ReceiveMessageAction.java:292)
> 	at com.consol.citrus.actions.ReceiveMessageAction.receive(ReceiveMessageAction.java:138)
> 	at com.consol.citrus.actions.ReceiveMessageAction.doExecute(ReceiveMessageAction.java:119)
> 	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:46)
> 	at com.consol.citrus.dsl.actions.DelegatingTestAction.doExecute(DelegatingTestAction.java:54)
> 	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:46)
> 	at com.consol.citrus.container.SequenceAfterSuite.doExecute(SequenceAfterSuite.java:50)
> 	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:46)
> 	at com.consol.citrus.Citrus.afterSuite(Citrus.java:360)
> 	at com.consol.citrus.junit.TestSuiteExecutionListener$AfterSuiteShutdownHook.run(TestSuiteExecutionListener.java:66)
> 	at java.lang.Thread.run(Thread.java:748)
> 16:08:32.047 [Thread-1] ERROR com.consol.citrus.container.SequenceAfterSuite - Continue after suite actions
> 16:08:32.047 [Thread-1] INFO com.consol.citrus.report.LoggingReporter - 
> 16:08:32.047 [Thread-1] INFO com.consol.citrus.report.LoggingReporter - AFTER TEST SUITE: FAILED

I tried searching the project for a @DirtiesContext annotation that could close the spring context but found nothing.

Help please

**Comment by svettwer** [comment]
Hi!

The `afterSuite` implementation looks good so far. The error states that the spring application context has already been closed when the actions are executed.
I'll try to reproduce the issue locally.

BR,
Sven

**Comment by svettwer** [comment]
Hi!

Unfortunately I was unable to reconstruct the issue locally with the current citrus version. 

I've implemented the following class:
```java
public class Foobar extends TestDesignerAfterSuiteSupport {

    public static final String CLIENT = "todo-client";

    @Override
    public void afterSuite(TestDesigner designer) {
        designer.echo("hi!!");
        designer.http().client(CLIENT)
                .send()
                .get("api/todolist");
        designer.http().client(CLIENT)
                .receive()
                .response(HttpStatus.OK);
    }
}
```

and this config:
```java
    @Bean("todo-client")
    public HttpClient httpClient(){
        return CitrusEndpoints.http().client().requestUrl("http://todo-app.paas.consol.de/").build();
    }

    @Bean
    public TestDesignerAfterSuiteSupport getFoobar(){
        return new Foobar();
    }
```

This works fine for me.
Which version of Citrus are you currently using?

It seems that something in your project is closing the spring context unexpected.
Have to tried to isolate the issue by limiting the amount of tests executed before the `TestDesignerAfterSuiteSupport` implementation kicks in?
Maybe a side effect of the test in manipulating the actual application context.

BR,
Sven

**Comment by GabrielShaukan** [comment]
Hi thank you for the replies.

I'm currently using the lastest version of Citrus (2.7.6).

I have tried limiting the amount of tests executed to one test and it still shows the error. I even tried an empty test and it still produces the same error. 

maybe the before suite has something to do with it, here are the classes run before suite:


    public class DeactivateAutomaticImportBeforeSuite extends TestDesignerBeforeSuiteSupport {
           
        public static final String SD_MANAGER_CLIENT_AUTH = "sdManagerClientAuth";
	
	    @Override
	     public void beforeSuite(TestDesigner designer) {
		    designer.http().client(SD_MANAGER_CLIENT_AUTH)
			    .send()
			    .post("import/disable-scheduling");
		    designer.http().client(SD_MANAGER_CLIENT_AUTH)
			    .receive()
			    .response(HttpStatus.OK);
		
	    }

    }

Another class 

    public class RemoveDataFromMariaDBBeforeSuite extends TestDesignerBeforeSuiteSupport{
	
	    @Autowired
	    @Qualifier("mariaDBDataSource")
	    private DataSource mariaDBDataSource;
	
	    @Override
	    public void beforeSuite(TestDesigner designer) {
				
		    designer.sql(mariaDBDataSource)
			    .statement("DELETE FROM tariff_article;")
			    .statement("DELETE FROM tariff_producttype;")
			    .statement("DELETE FROM tcm;") 
			    .statement("DELETE FROM article;")
			    .statement("DELETE FROM spin_product_type;")
			    .statement("DELETE FROM tariff;")
			    .statement("DELETE FROM staging_tcm;")
			    .statement("DELETE FROM spin_import_log;")
			    .statement("DELETE FROM tcm_import_log;");
	    }
    }

with this config 

    
	<bean id="beforeSuite"
		class="DeactivateAutomaticImportBeforeSuite" />
	<bean id="RemoveDataFromMariaDBBeforeSuite"
		class="RemoveDataFromMariaDBBeforeSuite" />
		
	
	 <bean id="afterSuite"
		class="ActivateAutomaticImportAfterSuite" />

**Comment by svettwer** [comment]
Hi!

Hmmm... that's strange... but it's a hint!
The `TestDesignerAfterSuiteSupport` interface does not close the spring context. The Citrus life cycle depends on a running spring context. That's why you get this error. In addition, as I tried to reconstruct the issue with some code from the citrus-samples project, everything worked as expected. The `TestDesignerBeforeSuiteSupport` implementations are okay as well.

So we're looking for something that closes the application context before the `TestDesignerAfterSuiteSupport` kicks in but after the `TestDesignerAfterTestSupport` is executed.

The log shows that the context has been closed but unfortunately this INFO message is very generic. So there is no information where the close operation came from. So it could basically be invoked from everywhere. That's what makes it hard to help remote on this one.

May there be another `TestDesignerAfterTestSupport` implementation that is manipulating the context?

BR,
Sven

**Comment by GabrielShaukan** [comment]
There are no `TestDesignerAfterTestSupport` implementations in the project. 

If I write an empty test, run it and the error still pops up that means that the problem is not in the tests right? Could the pom or the citrus-context.xml have anything to do with it ?

**Comment by GabrielShaukan** [comment]
Does `AfterTest` execute after every instance of  `@Test` in a class? Could i use it like AfterSuite ?

**Comment by svettwer** [comment]
Hi!
It's unlikely that the pom is the root cause but it could be useful if you post your context if possible.

Yes, `TestDesignerAfterTestSupport` is executed after every `@CitursTest` annotated method. It's a different use case but you could exchange the `TestDesignerBeforeSuiteSupport` with `TestDesignerBeforeTestSupport` and use `TestDesignerAfterTestSupport` instead of `TestDesignerAfterSuiteSupport`.
Nevertheless with a growing amount of tests, the steps are executed redundantly which will increase the time to run the tests.

BR,
Sven

**Comment by GabrielShaukan** [comment]
Unfortunately its not possible to post the context, how would i go about using TestDesignerAfterTestSupport after only one specific @CitrusTest? is that at all possible ?

**Comment by svettwer** [comment]
Hi!

It's possible to add filters for packages, classes etc.
Please have a look at the [after-test documentation](http://citrusframework.org/citrus/reference/html/index.html#after-test) for more information.
